### ISSUE TITLE
FileNotFoundError (possibly on plotting empty midi file)

### ISSUE THREAD

**Issue by hsapaul** [malcolmsailor/midani#1]
FileNotFoundError: [Errno 2] No such file or directory: 'midani_output\\Empty00001.png'

**Comment by hsapaul** [comment]
after this command: 
py -m midani --midi "C:\PATH\Empty.mid" --mpl

**Comment by malcolmsailor** [comment]
Hi, thanks for the issue!

Can you attach `Empty.mid` so I can try your command myself? Is it actually an empty midi file (that is, not containing any notes)? Maybe I don't handle such files gracefully.

Or otherwise I haven't tested on Windows (don't have a Windows machine) so it may be that the way I'm handling filenames isn't portable to Windows.

**Comment by malcolmsailor** [comment]
c54c3f2 adds a warning/graceful exit on trying to plot an empty midi file. 

If you weren't trying to plot an empty midi file, please let me know and I'll reopen.
